/*
 * In-tree CLN test that verifies bug 0002 (assert on peer-controlled
 * wally error) and the precondition for bugs 0003/0004 (psbt_add_output
 * returning NULL after the patch instead of asserting).
 *
 * Drop at: bitcoin/test/run-bug-verify-psbt.c
 */
#include "config.h"
#include "../psbt.c"
#include "../tx.c"
#include "../../wire/towire.c"
#include "../../wire/fromwire.c"
#include <assert.h>
#include <ccan/cast/cast.h>
#include <ccan/tal/tal.h>
#include <common/setup.h>
#include <stdio.h>

/* AUTOGENERATED MOCKS START */
/* AUTOGENERATED MOCKS END */

#define LOG(...) do { fprintf(stderr, "[bug-verify-psbt] " __VA_ARGS__); fflush(stderr); } while (0)

int main(int argc, char *argv[])
{
	common_setup(argv[0]);
	chainparams = chainparams_for_network("bitcoin");

	/* Build a small PSBT (1 input, 1 output slot). */
	struct wally_psbt *psbt = create_psbt(tmpctx, 1, 1, 0);
	assert(psbt != NULL);
	LOG("psbt initialised: num_outputs=%zu\n", psbt->num_outputs);

	/* Script must be tal-allocated because CLN's wally_tx_output uses
	 * tal_bytelen() on it. A stack array would assert inside tal. */
	u8 *script = tal_arrz(tmpctx, u8, 22);
	script[0] = 0x00;
	script[1] = 0x14;
	for (int i = 2; i < 22; i++) script[i] = (u8)i;
	struct amount_sat amt = AMOUNT_SAT(100000);

	LOG("calling wally_tx_output(tmpctx, script[len=%zu], 100000)\n",
	    tal_bytelen(script));
	struct wally_tx_output *tx_out = wally_tx_output(tmpctx, script, amt);
	LOG("wally_tx_output returned %p\n", (void *)tx_out);
	assert(tx_out != NULL);

	/* Direct call into psbt_add_output — the function the patch changes.
	 * insert_at = 999 forces wally_psbt_add_tx_output_at to return
	 * WALLY_EINVAL, exactly the condition the fuzzer-found tx_add_output
	 * (with serial_id ordering before existing outputs) hits. */
	LOG("calling psbt_add_output(psbt, tx_out, insert_at=999)\n");
	LOG("vanilla expected: assert fires inside psbt_add_output -> SIGABRT\n");
	LOG("patched expected: psbt_add_output returns NULL\n");

	struct wally_psbt_output *out = psbt_add_output(psbt, tx_out, 999);

	LOG("psbt_add_output returned %p\n", (void *)out);
	wally_tx_output_free(tx_out);

	if (out == NULL) {
		LOG("PATCHED OK: returned NULL cleanly (no assert, no NULL deref)\n");
		printf("PATCHED_OK\n");
		common_shutdown();
		return 0;
	}

	LOG("UNEXPECTED: got non-NULL pointer %p\n", (void *)out);
	printf("UNEXPECTED\n");
	common_shutdown();
	return 2;
}
